CFLAGS=-Wall -lm

all: teste1 teste2 teste3

teste1: teste1.c ../lib/ondas_lib.c

teste2: teste2.c ../lib/ondas_lib.c ../lib/alloc_safe.c ../lib/imagem.c ../lib/leitura_entrada.c ../lib/matriz.c

teste3: teste3.c ../lib/ondas_lib.c ../lib/alloc_safe.c ../lib/imagem.c ../lib/leitura_entrada.c ../lib/matriz.c
